### ISSUE TITLE
Please push changes for 0.3.0

### ISSUE THREAD

**Issue by asomers** [brain0/atomic_enum#11]
crates.io contains a verison 0.3.0 for atomic_enum.  But it isn't on Github.  Perhaps you forgot to push after building the release.  Could you please push?

**Comment by nyurik** [comment]
@brain0 hi, any updates on this? I would love to use this code, but if github and crates.io diverge, i am not certain what code is actually being maintained and where. Thx!

**Comment by brain0** [comment]
Very sorry, I keep missing GitHub notifications. I pushed the missing commits and added the missing tag.
